### PR TITLE
Add hashtags

### PR DESCRIPTION
**Pull request by clehner**

### CODE REVIEW

**Comment by clehner** [comment]
hey @pfrazee, could you add me or others from @ssbc as npm owner to ssb-marked?

**Comment by pfrazee** [comment]
Sure

**Comment by pfrazee** [comment]
Done

**Comment by clehner** [comment]
thanks

**Comment by dominictarr** [comment]
I ran the tests, and had one fail, this output appeared in the console.
```
#10. def_blocks.text failed at offset 20. Near: "<blockquote><p>hello</p><p><ahref="foo">1</a>:hell".


Got:
<blockquote><p>hello</p><p><ahref="foo">1</a>:hell


Expected:
<blockquote><p>hello[1]:hello</p></blockquote><hr>

```
aha, but that is broken on master anyway.

so I just *merged, into 0.7.0*

ps. we have two separate markdown modules - our fork of `marked` and `ssb-markdown`.
we should probably consolidate this into just one

**Comment by clehner** [comment]
yeah, that "hello" error has been there a while; i haven't investigated it lately but i recall it is manually specified to be ignored.

opened ssbc/ssb-markdown#18 to merge the changes towards clients

the api of (ssb-)marked is nice and extensible. individual renderer methods can be overridden, so it can work in different environments. the tests in ssb-markdown are easy to work with though.

**Pull request merged**
